"use client"

// import type { Metadata } from "next"

//NextAuth
import { SessionProvider } from "next-auth/react";

import "./globals.css";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


//Components
import Navbar from "./components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-workSans antialiased text-text bg-background`}
      >
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
